### PR TITLE
Added clean tasks to remove generated files

### PR DESCRIPTION
**Pull request by rgozim**
Clean tasks added for files generated by split tasks.

### CODE REVIEW

**Comment by jburel** [comment]
This PR has fixed the indent problem described here https://github.com/ome/omero-blitz/pull/7#issuecomment-453049119

**Comment by joshmoore** [comment]
@jburel : was there a conflict needing to merge in origin/master? If not, shall we just push that away and merge this PR?

**Comment by jburel** [comment]
No it was mainly to simplify the build. I should have used my branch instead. I will remove that commit

**Comment by jburel** [comment]
done

**Comment by joshmoore** [comment]
Great. Merging and updating https://github.com/ome/omero-gradle-plugins

**Pull request merged**
