### PR TITLE
Added config resolution fix for omero-model artifact

### PR DESCRIPTION
**Pull request by rgozim**
📺... 💥

### CODE REVIEW

**Comment by joshmoore** [comment]
* what's the difference between how you set `VERSION_1_8` here and in gh-7?
 * can you add a description of what this is intended to do and what testing is needed?
 * also, can you use a different branch name please?

**Comment by microscopepony** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by joshmoore** [comment]
@rgozim : if you get a chance, can you respond to this?

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by joshmoore** [comment]
@rgozim : ping again

**Comment by rgozim** [comment]
Going to close this PR as it's essentially done in m5 branch.

@joshmoore to answer the question regarding `java { targetCompatibility }` vs `targetCompatibility`, they're almost the same. Wrapping in `java {}` references the [JavaPluginExtension](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPluginExtension.html) directly, whereas setting `targetCompatibility` outside the java brackets sets the `JavaPluginConvention` setting. It will result in the same output, however `JavaPluginConvention` is the older gradle style(ism) which will _eventually_ be replaced by extension usage.

**Pull request closed without merging**
